spring:
  sql:
    init:
      mode: always
      encoding: UTF-8
  datasource:
    url: jdbc:h2:tcp://localhost/~/insurance
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
  jpa:
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false
